#ifndef CROWN_CHAINPARAMSSEEDS_H
#define CROWN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the crown network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x88,0xf4,0x6a,0xcf}, 20480},
};

static SeedSpec6 pnSeed6_test[] = {
};
#endif // CROWN_CHAINPARAMSSEEDS_H
